

const projects=[
{id:'real-estate-agent',icon:'RE',title:'Autonomous Real Estate Agent',type:'n8n automation',headline:'From first enquiry to a booked property viewing.',description:'A multi-channel agent handling property enquiries across voice and WhatsApp. It qualifies leads, retrieves matching listings, answers follow-up questions and schedules viewings with human escalation only when needed.',role:'AI architecture & automation',domain:'Real estate',outcome:'Zero-touch qualification and booking across two customer channels.',stack:['n8n','OpenAI','Vapi','Pinecone','LangChain'],flow:['Inbound lead','Intent & qualification','Listing retrieval','Viewing booked']},
{id:'techmen-sales',icon:'TS',title:'Techmen Sales Automation',type:'sales AI',headline:'Six enquiry types, one dependable sales workflow.',description:'An autonomous sales system that understands intent, captures CRM-ready lead data, prioritizes high-value opportunities and routes exceptional cases to the right person.',role:'Workflow engineering',domain:'B2B sales',outcome:'Faster response and consistent lead capture without manual triage.',stack:['n8n','OpenAI','Telegram','Google Sheets'],flow:['New enquiry','Intent routing','Lead scoring','CRM capture']},
{id:'dental-assistant',icon:'DC',title:'AI Dental Clinic Assistant',type:'voice & messaging AI',headline:'A patient conversation that ends with a confirmed appointment.',description:'A WhatsApp-based assistant that retrieves patient context, answers clinic questions, checks live availability and completes appointment booking end to end.',role:'Conversational AI',domain:'Healthcare',outcome:'Reduced front-desk workload while keeping the booking experience personal.',stack:['n8n','WhatsApp API','OpenAI','Calendar'],flow:['Patient message','History lookup','Availability check','Appointment booked']},
{id:'aviation-email',icon:'AV',title:'Jepsii Aviation Email Automation',type:'data extraction',headline:'High-volume aviation enquiries, structured and routed automatically.',description:'Built for Jepsii to sort aviation enquiries, extract key details, check for missing information, and route emails to the right team.',role:'Pipeline architecture',domain:'Aviation',outcome:'Cleaner case data and dramatically less manual email handling.',stack:['Python','n8n','OpenAI','Email APIs'],flow:['Email received','Classify & extract','Validate fields','Route case']},
{id:'voice-bot',icon:'VB',title:'Car Wash Voice Agent',type:'voice AI',headline:'A voice agent that explains, qualifies and books.',description:'An inbound and outbound calling agent that explains service packages, qualifies prospective customers, schedules appointments and logs the complete interaction to the CRM.',role:'Voice automation',domain:'Local services',outcome:'Always-on phone coverage with structured CRM records.',stack:['Vapi','n8n','OpenAI','CRM'],flow:['Call connected','Intent detected','Package selected','Booking logged']},
{id:'linkedin-profile-scraper',title:'LinkedIn Profile Scraper',description:'An n8n workflow that takes user requirements, searches LinkedIn profiles with SerpAPI, and collects matching profile information.',role:'Workflow development',domain:'Data extraction',stack:['n8n','SerpAPI'],flow:['User enters requirements','Search profiles with SerpAPI','Collect matching profile information']},
{id:'linkedin-publisher',icon:'LI',title:'LinkedIn AI Publisher',type:'content automation',headline:'From topic research to a scheduled post in one flow.',description:'A complete content workflow that researches relevant topics, drafts posts, creates supporting imagery and schedules approved content for publishing.',role:'Automation engineering',domain:'Content operations',outcome:'A repeatable publishing rhythm with less manual production effort.',stack:['n8n','Gemini','DALL-E','LinkedIn'],flow:['Topic research','Draft content','Create visual','Schedule post']},
{id:'rag-assistant',icon:'RA',title:'Private RAG Assistant',type:'knowledge intelligence',headline:'Useful answers without private data leaving the organization.',description:'A locally hosted knowledge agent that indexes internal documents and returns grounded, traceable answers while keeping sensitive repositories off external APIs.',role:'RAG engineering',domain:'Enterprise knowledge',outcome:'Secure natural-language access to private organizational knowledge.',stack:['Ollama','FastAPI','FAISS','LangChain'],flow:['Ingest documents','Create embeddings','Retrieve context','Grounded answer']},
{id:'logistics-dashboard',icon:'JE',title:'Jepsii Logistics Dashboard',type:'web application',headline:'Operational visibility for charter and fuel logistics.',description:'Built for Jepsii to track revenue, client activity, and logistics performance in one dashboard.',role:'Full-stack development',domain:'Logistics',outcome:'One clear operating picture for faster commercial decisions.',stack:['Next.js','React','Tailwind CSS','REST APIs'],flow:['Collect data','Normalize metrics','Calculate KPIs','Display insight']},
{id:'broad-peak',icon:'BP',title:'Broad Peak Adventures',type:'web experience',headline:'Adventure travel presented with a sense of place.',description:'An immersive tourism website for Northern Pakistan, combining destination storytelling with a fluid, mountain-inspired browsing experience.',role:'Frontend development',domain:'Travel',outcome:'A stronger visual identity and clearer path from discovery to enquiry.',stack:['React','Tailwind CSS','Vercel'],flow:['Discover region','Explore journeys','Review details','Send enquiry']},
{id:'autoencoder',icon:'CV',title:'PI-MF Autoencoder',type:'computer vision',headline:'Crowd-robust anomaly detection at edge speed.',description:'A physics-informed multi-modal fusion autoencoder combining pose, optical flow and appearance signals for live CCTV anomaly detection.',role:'AI research & engineering',domain:'Computer vision',outcome:'30+ FPS edge inference on RTX 3060 across a 150 GB dataset.',stack:['PyTorch','YOLOv8','ByteTrack','OpenCV'],flow:['Video stream','Extract modalities','Fuse signals','Flag anomaly']}
];

export default function Portfolio() {
  return <div className="container"><section className="page-header"><h1 className="page-title">Projects</h1><p className="page-desc">A selection of my work in AI, automation, and web development.</p></section><div className="project-grid">{projects.map(project => <article className="project-card" id={project.id} key={project.id}><p className="eyebrow">{project.domain}</p><h2>{project.title.replace('Autonomous ', '')}</h2><p>{project.description}</p>{project.stack.length > 0 && <div className="project-tools">{project.stack.map(tool => <span key={tool}>{tool}</span>)}</div>}<details><summary>Project details</summary><p><strong>My role:</strong> {project.role}</p>{project.outcome && <p>{project.outcome}</p>}{project.flow.length > 0 && <ol>{project.flow.map(step => <li key={step}>{step}</li>)}</ol>}</details></article>)}</div></div>;
}




